include "common.conf"

pulsar {
  consumer {
    # Enable multiple topics in case the source is duplicated already to two topics.
    # Functionality of this application should not need any changes.
    multipleTopics=false
    multipleTopics=${?PULSAR_CONSUMER_ENABLE_MULTIPLE_TOPICS}
    topicsPattern=""
    topicsPattern=${?PULSAR_CONSUMER_MULTIPLE_TOPICS_PATTERN}
    # Let's use single topic as default
    topic="hfp-data"
    topic=${?PULSAR_CONSUMER_TOPIC}
    subscription="hfp-dedup-subscription"
    subscription=${?PULSAR_CONSUMER_SUBSCRIPTION}
  }
  producer {
    topic="hfp-dedup-data"
    topic=${?PULSAR_PRODUCER_TOPIC}
  }
}

application {
  # How to estimate the cache TTL:
  #
  # There could be timeouts between MQTT broker and its client and Pulsar broker
  # and its client. Let's say 2 * 3 min to be on the safe side.
  #
  # There are restart times of pods, let's say 2 min.
  #
  # Network partitions might occur for hours in a way that mqtt-pulsar-gateway
  # gathers data from the MQTT broker but does not produce them to Pulsar. The
  # MQTT protocol limits the number of messages in-flight, also the limit for
  # unacknowledeged messages, to about 2**16~=65k. mqtt-pulsar-gateway should be
  # smart enough that if it cannot push messages to Pulsar within, say, 10
  # minutes, it should exit. mqtt-pulsar-gateway should also have cleanSession
  # set to true so that reconnection does not repeat old messages. We have
  # replicas running so that is not a problem.
  #
  # Total 2*3+2+10=18 min. Let's round it upwards to 20 min.
  #
  # According to calculated statistics on locally-collected HFP data, the 99.9th
  # percentile of message count within a minute is around 110_000 messages. So
  # 20 minutes of caching would mean 20 * 110_000 = 2_200_000 elements. Let's
  # round it to 2_500_000 elements.
  #
  # So max cache size should be 2_500_000. Starting cache size could be for 1
  # min, so about 100_000 elements. And cache TTL should be 20 min.
  cacheTTL = 20 minutes
  cacheTTL=${?CACHE_TTL}
  cacheSize = 2500000
  cacheSize = ${?CACHE_SIZE}
  alert {
    pollInterval = 1 minutes
    pollInterval=${?ALERT_POLL_INTERVAL}
    duplicateRatioThreshold = 0.97
    duplicateRatioThreshold=${?ALERT_DUPLICATE_RATIO_THRESHOLD}
    alertOnThreshold = true
    alertOnThreshold=${?ALERT_ON_RATIO_THRESHOLD}
    alertOnDuplicate = false
    alertOnDuplicate=${?ALERT_ON_DUPLICATE}
  }
}
